### ISSUE TITLE
Any objections to an Underscore fork?

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash3#15]
I started work on https://github.com/captbaritone/eslint-plugin-underscore, and only after getting the first rule complete did I discover this project. I think a better approach would be for me to fork this project and remove/modify all the Underscore-specific bits.

Would there be any objections to creating a fork for this purpose?

**Comment by ganimomer** [comment]
Go right ahead!
Let us know if there's anything we can do to help.

**Comment by captbaritone** [comment]
Thanks!

**Comment by captbaritone** [comment]
FYI: I've gone ahead with the fork: https://github.com/captbaritone/eslint-plugin-underscore
