### ISSUE TITLE
Prefer lodash functions over native javascript

### ISSUE THREAD

**Issue by cafesanu** [wix/eslint-plugin-lodash3#3]
Just what I was looking for! Thanks!

Would be awesome to have rules to set lodash `forEach`/`isArray`/`isObject`/`isString`/`isBoolean`/etc over native javascript. Similar to what https://github.com/Gillespie59/eslint-plugin-angular did with `typecheck-array`/`typecheck-date`/`typecheck-number`/`typecheck-object`/etc.

Thanks and nice job!

**Comment by ganimomer** [comment]
Sounds good! We'll add it to our backlog. You're welcome to submit a PR yourself.

**Comment by ganimomer** [comment]
Implemented rules `prefer-lodash-method` and `prefer-lodash-typecheck` for your convenience!
Available from v0.1.8.

**Comment by cafesanu** [comment]
Thanks!
