### ISSUE TITLE
Logical problem with prefer-lodash-typecheck

### ISSUE THREAD

**Issue by mik01aj** [wix/eslint-plugin-lodash3#5]
`typeof` typechecks are not always equivalent to lodash ones. Consider this example:

![image](https://cloud.githubusercontent.com/assets/3027415/10764481/c47508fe-7cce-11e5-9ac4-3ff6d1a7e9b2.png)

I'd like to disable the `prefer-lodash-typecheck` for `typeof` checks against `"undefined"`.

**Comment by ganimomer** [comment]
Thanks! Fixed in v0.1.13

**Comment by mik01aj** [comment]
:+1:  thanks!
