### ISSUE TITLE
jQuery-like find mistook for native find

### ISSUE THREAD

**Issue by gajus** [wix/eslint-plugin-lodash3#9]
```js
$(movieElement)
    .parents('h3')
    .siblings('.show_results')
    .find('.film_time_listing span a')
```

This is a [cheerio](https://github.com/cheeriojs/cheerio) object iteration.

```
║ 32       │ 57       │ warning  │ Prefer '_.find' over the native function               │ lodash3/prefer-      ║
║          │          │          │                                                        │ lodash-method        ║
║ 34       │ 36       │ warning  │ Prefer '_.find' over the native function               │ lodash3/prefer-      ║
║          │          │          │                                                        │ lodash-method        ║
║ 35       │ 32       │ warning  │ Prefer '_.find' over the native function               │ lodash3/prefer-      ║
║          │          │          │                                                        │ lodash-method        ║
║ 36       │ 33       │ warning  │ Prefer '_.find' over the native function               │ lodash3/prefer-      ║
║          │          │          │                                                        │ lodash-method        ║
║ 46       │ 36       │ warning  │ Prefer '_.find' over the native function               │ lodash3/prefer-      ║
║          │          │          │                                                        │ lodash-method        ║
```

It results in the following errors.

**Comment by gajus** [comment]
I cannot think of how to fix this at the AST level.

**Comment by ganimomer** [comment]
Neither can we. At the AST level, there's no way of knowing that `$(movieElement).parents('h3').siblings('.show_results')` **isn't** an array, and this plugin should be library agnostic, except for Lodash itself.
I guess I would advise to turn off this rule for corresponding lines, files, or folders in general.

**Comment by gajus** [comment]
Technically, you could add a check if the top-most node in the chain is `$()` declaration.

99% of the code that relies on jQuery like DOM iterators use this convention.

**Comment by gajus** [comment]
It gets a bit harder if you do something like this:

```js
$(movieElement)
    .parents('h3')
    .siblings('.show_results')
    .find('.film_time_listing span a')
    [0]
    .find(conditionFn)
```

**Comment by ganimomer** [comment]
Yes, technically we could. However, Like I said, the plugin doesn't assume anything about variables by their names except for Lodash. There could technically be a $() definition in which the `find` is the native ES6 `Array.prototype.find`.
In general, we have no way of knowing that any method that's named like an array method isn't used on an array.
Again, in this case I think you should disable this specific rule.

**Comment by gajus** [comment]
There is no way to disable it just for "find" and otherwise this is the only rule that I find useful.

**Comment by gajus** [comment]
This also breaks when using http://bluebirdjs.com/docs/api-reference.html. There is no obvious solution. Shame, in theory it is a nice linting rule. In practise it is just not functional.

**Comment by gajus** [comment]
I wonder how feasible would it be to define something like this in a run-time setup.

**Comment by mik01aj** [comment]
:+1:  +1 for adding configuration to this rule so that we can disable it just for `find`.

**Comment by gajus** [comment]
For the record, I never suggested to disable this rule just for find and I think thats a bad idea.
